CREATE TABLE `company_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`tradeName` varchar(255),
	`cnpj` varchar(20) NOT NULL,
	`stateRegistration` varchar(50),
	`municipalRegistration` varchar(50),
	`address` text,
	`neighborhood` varchar(100),
	`city` varchar(100),
	`state` varchar(2),
	`zipCode` varchar(20),
	`phone` varchar(50),
	`email` varchar(255),
	`website` varchar(255),
	`ownerName` varchar(255),
	`ownerCpf` varchar(20),
	`ownerRole` varchar(100),
	`ownerNationality` varchar(50) DEFAULT 'brasileiro',
	`ownerMaritalStatus` varchar(50),
	`ownerProfession` varchar(100),
	`ownerAddress` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_settings_id` PRIMARY KEY(`id`)
);
